import api from "./api";
export const getUsers = () => api.get("/users");
export const getAdminCharities = (params) => api.get("/charities", { params });
export const getAdminDraws = () => api.get("/draws");
export const getAdminWinners = () => api.get("/winners/admin/all");
export const getDashboardReport = () => api.get("/reports/dashboard");
export const getSubscriptionReport = () => api.get("/reports/subscriptions");
export const getWinnerReport = () => api.get("/reports/winners");
export const getCharityReport = () => api.get("/reports/charities");
export const getDrawReport = () => api.get("/reports/draws");
export const createUser = (data) => api.post("/users", data);
export const updateUser = (id, data) => api.put(`/users/${id}`, data);
export const deleteUser = (id) => api.delete(`/users/${id}`);
export const createCharity = (data) => api.post("/charities", data);
export const updateCharity = (id, data) => api.put(`/charities/${id}`, data);
export const deleteCharity = (id) => api.delete(`/charities/${id}`);
export const toggleCharityStatus = (id) => api.patch(`/charities/${id}/status`);
export const toggleFeaturedCharity = (id) => api.patch(`/charities/${id}/featured`);
export const createDraw = (data) => api.post("/draws", data);
export const updateDraw = (id, data) => api.put(`/draws/${id}`, data);
export const deleteDraw = (id) => api.delete(`/draws/${id}`);
export const simulateDraw = (id) => api.post(`/draws/${id}/simulate`);
export const publishDraw = (id) => api.post(`/draws/${id}/publish`);
export const completeDraw = (id) => api.post(`/draws/${id}/complete`);
export const getAdminWinnerProof = (id) => api.get(`/winners/${id}/proof`);
export const verifyAdminWinner = (id, data) => api.patch(`/winners/admin/${id}/verify`, data);
export const markAdminWinnerPaid = (id) => api.patch(`/winners/admin/${id}/pay`);
export const deleteAdminWinner = (id) => api.delete(`/winners/admin/${id}`);
