import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, CircleDollarSign, Gift, HeartHandshake, Medal, Trophy, Users as UsersIcon } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState, ErrorState, InlineLoading } from "../components/UiStates";
import { getDashboardReport } from "../services/adminService";
import { apiMessage, currencyValue } from "../pages/memberUtils";
import "./AdminPages.css";

export default function AdminDashboard() {
  const [dashboard, setDashboard] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const { data } = await getDashboardReport(); setDashboard(data.dashboard || null); } catch (requestError) { setError(apiMessage(requestError, "We couldn’t load the administration overview.")); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  if (loading) return <section className="admin-page"><div className="admin-card"><InlineLoading label="Loading administration overview…" /></div></section>;
  if (error || !dashboard) return <section className="admin-page"><header className="admin-header"><p className="page-eyebrow">Administration</p><h1>Digital Heroes admin.</h1></header><div className="admin-card"><ErrorState message={error || "Dashboard data is unavailable."} onRetry={load} /></div></section>;
  const metrics = [["Users", dashboard.users?.total, UsersIcon, "/admin/users"], ["Active subscriptions", dashboard.subscriptions?.active, HeartHandshake, null], ["Charities", dashboard.charities?.total, HeartHandshake, "/admin/charities"], ["Draws", dashboard.draws?.total, Gift, null], ["Winners", dashboard.winners?.total, Medal, null], ["Donation total", currencyValue(dashboard.donations?.total_amount), CircleDollarSign, null], ["Prize pool total", currencyValue(dashboard.prize_pool?.total_amount), Trophy, null]];
  return <section className="admin-page"><header className="admin-header"><div><p className="page-eyebrow">Administration</p><h1>Digital Heroes admin.</h1><p>Live operational information from the current Digital Heroes records.</p></div></header><div className="admin-metric-grid">{metrics.map(([label, value, Icon, path]) => <article className="admin-card admin-metric" key={label}><Icon size={21} /><span>{label}</span><strong>{value ?? "Unavailable"}</strong>{path && <Link className="text-action" to={path}>Manage <ArrowRight size={15} /></Link>}</article>)}</div><div className="admin-detail-grid"><article className="admin-card"><h2>Draw and winner status</h2><div className="admin-detail-list"><div><span>Completed draws</span><strong>{dashboard.draws?.completed ?? "Unavailable"}</strong></div><div><span>Winners awaiting verification</span><strong>{dashboard.winners?.pending ?? "Unavailable"}</strong></div><div><span>Paid winners</span><strong>{dashboard.winners?.paid ?? "Unavailable"}</strong></div></div></article><article className="admin-card"><h2>Quick actions</h2><p>Manage the people, causes, draws and records that power Digital Heroes.</p><div className="admin-quick-actions"><Link className="action-button" to="/admin/users"><UsersIcon size={17} /> Users</Link><Link className="quiet-button" to="/admin/charities"><HeartHandshake size={17} /> Charities</Link><Link className="quiet-button" to="/admin/draws"><Gift size={17} /> Draws</Link><Link className="quiet-button" to="/admin/winners"><Medal size={17} /> Winners</Link><Link className="quiet-button" to="/admin/reports"><BarChart3 size={17} /> Reports</Link></div></article></div></section>;
}
