import { useEffect, useState } from "react";
import { HeartHandshake, Pencil, Plus, Star, Trash2 } from "lucide-react";
import { ConfirmationDialog, EmptyState, ErrorState, InlineLoading } from "../components/UiStates";
import { createCharity, deleteCharity, getAdminCharities, toggleCharityStatus, toggleFeaturedCharity, updateCharity } from "../services/adminService";
import { apiMessage } from "../pages/memberUtils";
import "./AdminPages.css";
import "./AdminCharityFilters.css";

const freshForm = { name: "", description: "", image_url: "", website_url: "", is_active: true, is_featured: false };
export default function CharityManagement() {
  const [charities, setCharities] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [filters, setFilters] = useState({ search: "", active: "", featured: "" }), [form, setForm] = useState(freshForm), [formError, setFormError] = useState(""), [success, setSuccess] = useState(""), [saving, setSaving] = useState(false), [editing, setEditing] = useState(null), [deleteTarget, setDeleteTarget] = useState(null), [deleting, setDeleting] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { const params = { ...(filters.search.trim() ? { search: filters.search.trim() } : {}), ...(filters.active ? { active: filters.active } : {}), ...(filters.featured ? { featured: filters.featured } : {}) }; const { data } = await getAdminCharities(params); setCharities(data.charities || []); } catch (requestError) { setError(apiMessage(requestError, "We couldn’t load charities.")); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [filters]);
  const resetForm = () => { setForm(freshForm); setEditing(null); setFormError(""); };
  const submit = async (event) => { event.preventDefault(); setFormError(""); setSuccess(""); if (!form.name.trim() || !form.description.trim()) return setFormError("Name and description are required."); setSaving(true); try { const payload = { name: form.name.trim(), description: form.description.trim(), image_url: form.image_url.trim() || null, website_url: form.website_url.trim() || null, is_active: form.is_active, is_featured: form.is_featured }; const { data } = editing ? await updateCharity(editing.id, payload) : await createCharity(payload); setSuccess(data.message || (editing ? "Charity updated successfully." : "Charity created successfully.")); resetForm(); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t save this charity.")); } finally { setSaving(false); } };
  const beginEdit = (charity) => { setEditing(charity); setForm({ name: charity.name || "", description: charity.description || "", image_url: charity.image_url || "", website_url: charity.website_url || "", is_active: Boolean(charity.is_active), is_featured: Boolean(charity.is_featured) }); setFormError(""); setSuccess(""); };
  const toggleStatus = async (charity) => { setFormError(""); try { const { data } = await toggleCharityStatus(charity.id); setSuccess(data.message || "Charity status updated successfully."); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t update this charity.")); } };
  const toggleFeatured = async (charity) => { setFormError(""); try { const { data } = await toggleFeaturedCharity(charity.id); setSuccess(data.message || "Charity featured status updated successfully."); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t update this charity.")); } };
  const confirmDelete = async () => { if (!deleteTarget) return; setDeleting(true); try { const { data } = await deleteCharity(deleteTarget.id); setSuccess(data.message || "Charity deleted successfully."); setDeleteTarget(null); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t delete this charity.")); setDeleteTarget(null); } finally { setDeleting(false); } };
  if (loading) return <section className="admin-page"><div className="admin-card"><InlineLoading label="Loading charities…" /></div></section>;
  return <section className="admin-page"><header className="admin-header"><div><p className="page-eyebrow">Administration</p><h1>Charity management.</h1><p>Maintain the charity directory and the charities highlighted to members.</p></div></header>{formError && <div className="form-error">{formError}</div>}{success && <div className="form-success">{success}</div>}
    <div className="admin-split-layout"><article className="admin-card admin-form-card"><div className="card-heading"><h2>{editing ? "Edit charity" : "Create charity"}</h2><HeartHandshake size={21} /></div><form onSubmit={submit}><div className="admin-form-fields"><label className="form-field">Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label className="form-field">Description<textarea required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label className="form-field">Image URL (optional)<input type="url" value={form.image_url} onChange={(event) => setForm({ ...form, image_url: event.target.value })} /><span className="field-help">Add a public image URL to display a charity image.</span></label><label className="form-field">Website URL (optional)<input type="url" value={form.website_url} onChange={(event) => setForm({ ...form, website_url: event.target.value })} /></label><label className="checkbox-field"><input type="checkbox" checked={form.is_active} onChange={(event) => setForm({ ...form, is_active: event.target.checked })} /> Active charity</label><label className="checkbox-field"><input type="checkbox" checked={form.is_featured} onChange={(event) => setForm({ ...form, is_featured: event.target.checked })} /> Featured charity</label></div><div className="form-actions"><button className="action-button" disabled={saving}>{saving ? <InlineLoading label="Saving…" /> : <><Plus size={17} /> {editing ? "Save changes" : "Create charity"}</>}</button>{editing && <button type="button" className="quiet-button" onClick={resetForm}>Cancel</button>}</div></form></article>
      <article className="admin-card admin-charity-list"><div className="card-heading"><h2>Charities</h2><HeartHandshake size={21} /></div><div className="admin-charity-filters"><input aria-label="Search charities" placeholder="Search charities" value={filters.search} onChange={(event) => setFilters({ ...filters, search: event.target.value })} /><select aria-label="Filter active status" value={filters.active} onChange={(event) => setFilters({ ...filters, active: event.target.value })}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select><select aria-label="Filter featured status" value={filters.featured} onChange={(event) => setFilters({ ...filters, featured: event.target.value })}><option value="">All charities</option><option value="true">Featured</option><option value="false">Not featured</option></select></div>{error ? <ErrorState message={error} onRetry={load} /> : charities.length ? <div className="admin-charity-cards">{charities.map((charity) => <article className="admin-charity-row" key={charity.id}>{charity.image_url ? <img src={charity.image_url} alt="" onError={(event) => { event.currentTarget.style.display = "none"; }} /> : <div className="admin-charity-placeholder"><HeartHandshake size={19} /></div>}<div className="admin-charity-content"><strong>{charity.name}</strong><p>{charity.description}</p><div className="admin-charity-badges"><button className={`status-badge status-button ${charity.is_active ? "active" : "inactive"}`} onClick={() => toggleStatus(charity)}>{charity.is_active ? "Active" : "Inactive"}</button><button className={`status-badge status-button ${charity.is_featured ? "featured" : ""}`} onClick={() => toggleFeatured(charity)}><Star size={12} /> {charity.is_featured ? "Featured" : "Not featured"}</button></div></div><div className="admin-row-actions"><button className="icon-button" aria-label={`Edit ${charity.name}`} onClick={() => beginEdit(charity)}><Pencil size={16} /></button><button className="icon-button danger-icon" aria-label={`Delete ${charity.name}`} onClick={() => setDeleteTarget(charity)}><Trash2 size={16} /></button></div></article>)}</div> : <EmptyState title="No charities found." message="Adjust the filters or create a charity to add one." />}</article></div><ConfirmationDialog open={Boolean(deleteTarget)} title="Delete this charity?" message="This permanently removes the selected charity record." confirmLabel={deleting ? "Deleting…" : "Delete charity"} onConfirm={confirmDelete} onCancel={() => !deleting && setDeleteTarget(null)} /></section>;
}
