import { useEffect, useState } from "react";
import { Pencil, Plus, ShieldCheck, Trash2, UserCheck, Users as UsersIcon } from "lucide-react";
import { ConfirmationDialog, EmptyState, ErrorState, InlineLoading } from "../components/UiStates";
import { createUser, deleteUser, getUsers, updateUser } from "../services/adminService";
import { apiMessage, formatDate, statusLabel } from "../pages/memberUtils";
import "./AdminPages.css";

const freshForm = { name: "", email: "", password: "", role: "user" };
export default function Users() {
  const [users, setUsers] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [form, setForm] = useState(freshForm), [formError, setFormError] = useState(""), [success, setSuccess] = useState(""), [saving, setSaving] = useState(false), [editing, setEditing] = useState(null), [deleteTarget, setDeleteTarget] = useState(null), [statusTarget, setStatusTarget] = useState(null), [deleting, setDeleting] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { const { data } = await getUsers(); setUsers(data.users || []); } catch (requestError) { setError(apiMessage(requestError, "We couldn’t load users.")); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const resetForm = () => { setForm(freshForm); setEditing(null); setFormError(""); };
  const submit = async (event) => { event.preventDefault(); setFormError(""); setSuccess(""); if (!form.name.trim() || !form.email.trim()) return setFormError("Name and email are required."); if (!editing && form.password.length < 6) return setFormError("A password of at least 6 characters is required."); if (editing && form.password && form.password.length < 6) return setFormError("A replacement password must be at least 6 characters."); setSaving(true); try { const payload = { name: form.name.trim(), email: form.email.trim(), role: form.role, ...(form.password ? { password: form.password } : {}) }; const { data } = editing ? await updateUser(editing.id, payload) : await createUser(payload); setSuccess(data.message || (editing ? "User updated successfully." : "User created successfully.")); resetForm(); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t save this user.")); } finally { setSaving(false); } };
  const beginEdit = (user) => { setEditing(user); setForm({ name: user.name || "", email: user.email || "", password: "", role: user.role || "user" }); setFormError(""); setSuccess(""); };
  const confirmToggleActive = async () => { if (!statusTarget) return; setSaving(true); setFormError(""); setSuccess(""); try { const { data } = await updateUser(statusTarget.id, { is_active: !statusTarget.is_active }); setSuccess(data.message || "User status updated successfully."); setStatusTarget(null); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t update this user.")); setStatusTarget(null); } finally { setSaving(false); } };
  const confirmDelete = async () => { if (!deleteTarget) return; setDeleting(true); try { const { data } = await deleteUser(deleteTarget.id); setSuccess(data.message || "User deleted successfully."); setDeleteTarget(null); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t delete this user.")); setDeleteTarget(null); } finally { setDeleting(false); } };
  if (loading) return <section className="admin-page"><div className="admin-card"><InlineLoading label="Loading users…" /></div></section>;
  return <section className="admin-page"><header className="admin-header"><div><p className="page-eyebrow">Administration</p><h1>User management.</h1><p>Create and maintain Digital Heroes member accounts.</p></div></header>{formError && <div className="form-error">{formError}</div>}{success && <div className="form-success">{success}</div>}
    <div className="admin-split-layout"><article className="admin-card admin-form-card"><div className="card-heading"><h2>{editing ? "Edit user" : "Create user"}</h2><UsersIcon size={21} /></div><form onSubmit={submit}><div className="admin-form-fields"><label className="form-field">Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label className="form-field">Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label className="form-field">{editing ? "New password (optional)" : "Password"}<input required={!editing} type="password" minLength="6" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label><label className="form-field">Role<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="user">User</option><option value="admin">Admin</option></select></label></div><div className="form-actions"><button className="action-button" disabled={saving}>{saving ? <InlineLoading label="Saving…" /> : <><Plus size={17} /> {editing ? "Save changes" : "Create user"}</>}</button>{editing && <button type="button" className="quiet-button" onClick={resetForm}>Cancel</button>}</div></form></article>
      <article className="admin-card admin-table-card"><div className="card-heading"><h2>Accounts</h2><UserCheck size={21} /></div>{error ? <ErrorState message={error} onRetry={load} /> : users.length ? <div className="admin-table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Created</th><th aria-label="Actions" /></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><strong>{user.name}</strong><span>{user.email}</span></td><td><span className="status-badge">{statusLabel(user.role)}</span></td><td><button className={`status-badge status-button ${user.is_active ? "active" : "inactive"}`} onClick={() => setStatusTarget(user)}>{user.is_active ? "Active" : "Inactive"}</button></td><td>{formatDate(user.created_at) || "Unavailable"}</td><td><div className="admin-row-actions"><button className="icon-button" aria-label={`Edit ${user.name}`} onClick={() => beginEdit(user)}><Pencil size={16} /></button><button className="icon-button danger-icon" aria-label={`Delete ${user.name}`} onClick={() => setDeleteTarget(user)}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div> : <EmptyState title="No users found." message="Create an account to add the first user." />}</article></div><ConfirmationDialog open={Boolean(statusTarget)} title={statusTarget?.is_active ? "Deactivate this user?" : "Activate this user?"} message={statusTarget?.is_active ? "A deactivated account can no longer access Digital Heroes until it is reactivated." : "This account will be able to access Digital Heroes again."} confirmLabel={saving ? "Saving…" : statusTarget?.is_active ? "Deactivate user" : "Activate user"} onConfirm={confirmToggleActive} onCancel={() => !saving && setStatusTarget(null)} /><ConfirmationDialog open={Boolean(deleteTarget)} title="Delete this user?" message="This permanently deletes the selected account. Your own admin account cannot be deleted by the system." confirmLabel={deleting ? "Deleting…" : "Delete user"} onConfirm={confirmDelete} onCancel={() => !deleting && setDeleteTarget(null)} /></section>;
}
