import { useEffect, useState } from "react";
import { ArrowRight, HeartHandshake, Search } from "lucide-react";
import { Link } from "react-router-dom";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { EmptyState, ErrorState, InlineLoading } from "../components/UiStates";
import { getCharities } from "../services/charityService";
import { apiMessage } from "./memberUtils";
import "./CharityPages.css";

function CharityCardImage({ charity }) { const [failed, setFailed] = useState(false); return <div className="charity-card-image">{charity.image_url && !failed ? <img src={charity.image_url} alt={charity.name} onError={() => setFailed(true)} /> : <HeartHandshake size={38} aria-label="Charity" />}</div>; }
function Charities() {
  const [search, setSearch] = useState(""), [featured, setFeatured] = useState(""), [active, setActive] = useState("true");
  const [charities, setCharities] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const loadCharities = async () => { setLoading(true); setError(""); try { const params = {}; if (search.trim()) params.search = search.trim(); if (featured) params.featured = featured; if (active) params.active = active; const { data } = await getCharities(params); setCharities(data.charities || []); } catch (requestError) { setError(apiMessage(requestError, "We couldn’t load charities right now. Please try again.")); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(loadCharities, 300); return () => window.clearTimeout(timer); }, [search, featured, active]);
  return <><Navbar /><main className="charity-page"><header className="charity-page-header"><p className="page-eyebrow">Causes that matter</p><h1>Find a charity to champion.</h1><p>Discover the organisations connected to Digital Heroes and choose a cause that feels personal.</p></header><section className="charity-controls" aria-label="Charity filters"><label className="charity-search"><span><Search size={14} /> Search charities</span><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by charity name" /></label><label className="charity-control-label">Availability<select className="charity-select" value={active} onChange={(event) => setActive(event.target.value)}><option value="true">Active</option><option value="">All</option><option value="false">Inactive</option></select></label><label className="charity-control-label">Feature<select className="charity-select" value={featured} onChange={(event) => setFeatured(event.target.value)}><option value="">All charities</option><option value="true">Featured</option></select></label></section>{loading ? <div className="charity-state"><InlineLoading label="Finding charities…" /></div> : error ? <div className="charity-state"><ErrorState message={error} onRetry={loadCharities} /></div> : charities.length === 0 ? <div className="charity-state"><EmptyState title="No charities found." message="Try adjusting your search or filters." /></div> : <><p className="charity-results">{charities.length} {charities.length === 1 ? "charity" : "charities"} found</p><section className="charity-grid-page">{charities.map((charity) => <article className="charity-directory-card" key={charity.id}><CharityCardImage charity={charity} /><div className="charity-card-body"><div className="charity-card-tags">{charity.is_featured && <span className="charity-tag">Featured</span>}{charity.is_active === false && <span className="charity-tag inactive">Inactive</span>}</div><h2>{charity.name}</h2>{charity.description && <p>{charity.description}</p>}<Link className="charity-card-link" to={`/charities/${charity.id}`}>Learn about this charity <ArrowRight size={16} /></Link></div></article>)}</section></>}</main><Footer /></>;
}
export default Charities;
