import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, CircleDollarSign, HeartHandshake, Trophy } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState, ErrorState, InlineLoading } from "../components/UiStates";
import { useAuth } from "../context/AuthContext";
import { getDonations } from "../services/donationService";
import { getDraws } from "../services/drawService";
import { getScores } from "../services/scoreService";
import { getSubscriptions } from "../services/subscriptionService";
import { getWinners } from "../services/winnerService";
import { apiMessage, currencyValue, formatDate, statusLabel } from "./memberUtils";
import "./MemberPages.css";

const latest = (items = []) => items[0] || null;
export default function Dashboard() {
  const { user } = useAuth(); const [data, setData] = useState({}), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); const results = await Promise.allSettled([getSubscriptions(), getScores(), getDonations(), getDraws(), getWinners()]); const keys = ["subscriptions", "scores", "donations", "draws", "winners"]; const next = {}; const errors = []; results.forEach((result, index) => { if (result.status === "fulfilled") next[keys[index]] = result.value.data[keys[index]] || [];       else { next[keys[index]] = []; errors.push(apiMessage(result.reason, `Some ${keys[index]} information isn’t available right now.`)); } }); setData(next); setError(errors.length ? "Some dashboard information isn’t available right now. You can still use the rest of your member tools." : ""); setLoading(false); };
  useEffect(() => { load(); }, []);
  if (loading) return <section className="member-page"><div className="member-card"><InlineLoading label="Loading your dashboard…" /></div></section>;
  const subscription = latest(data.subscriptions); const activeSubscription = data.subscriptions?.find((item) => item.status === "active"); const featuredSubscription = activeSubscription || subscription;
  const charity = featuredSubscription?.charities || latest(data.donations)?.charities; const recentScores = data.scores || []; const latestDonation = latest(data.donations); const currentDraw = (data.draws || []).find((draw) => ["published", "simulated", "draft"].includes(draw.status)) || latest(data.draws); const latestWinner = latest(data.winners);
  return <section className="member-page"><header className="member-header"><div><p className="page-eyebrow">Your impact</p><h1>Welcome back{user?.name ? `, ${user.name.split(" ")[0]}` : ""}.</h1><p>Your subscription, recent golf scores and the charity you support — all in one place.</p></div><div className="member-actions"><Link className="action-button" to="/scores"><Trophy size={16} /> Add score</Link><Link className="quiet-button" to="/subscription">View subscription</Link></div></header>{error && <div className="page-error"><ErrorState message={error} onRetry={load} /></div>}
    <div className="member-grid"><article className="member-card hero-card"><h2>{featuredSubscription ? "Your subscription at a glance." : "Your Digital Heroes journey starts here."}</h2><p>{featuredSubscription ? `Your ${featuredSubscription.plan_type || "member"} subscription is ${statusLabel(featuredSubscription.status)}.` : "You don’t have a subscription yet. Subscribe to choose a charity and join the monthly draw."}</p>{featuredSubscription && <span className={`status-badge ${featuredSubscription.status}`}>{statusLabel(featuredSubscription.status)}</span>}</article>
      <article className="member-card subscription-card"><div className="card-heading"><h2>Subscription</h2><CircleDollarSign size={21} /></div>{featuredSubscription ? <><div className="detail-list"><div className="detail-line"><span>Plan</span><strong>{statusLabel(featuredSubscription.plan_type)}</strong></div><div className="detail-line"><span>Status</span><strong>{statusLabel(featuredSubscription.status)}</strong></div>{featuredSubscription.renewal_date && <div className="detail-line"><span>Renewal date</span><strong>{formatDate(featuredSubscription.renewal_date)}</strong></div>}{featuredSubscription.amount !== undefined && <div className="detail-line"><span>Amount</span><strong>{currencyValue(featuredSubscription.amount, featuredSubscription.currency)}</strong></div>}</div><Link className="text-action" to="/subscription">View subscription <ArrowRight size={15} /></Link></> : <EmptyState title="No subscription yet." message="Subscribe to support a charity and enter monthly draws." />}</article>
      <article className="member-card impact-card"><div className="card-heading"><h2>Your charity</h2><HeartHandshake size={21} /></div>{charity ? <><div className="charity-preview">{charity.image_url && <img src={charity.image_url} alt="" />}<div><strong>{charity.name}</strong>{featuredSubscription?.charity_percentage !== undefined && <span>{featuredSubscription.charity_percentage}% contribution</span>}</div></div>{latestDonation?.amount !== undefined && <div className="detail-line"><span>Latest donation</span><strong>{currencyValue(latestDonation.amount, latestDonation.currency)}</strong></div>}<Link className="text-action" to={`/charities/${charity.id}`}>View charity <ArrowRight size={15} /></Link></> : <EmptyState title="No charity selected yet." message="Choose a charity when you subscribe." />}</article>
      <article className="member-card scores-card"><div className="card-heading"><h2>Latest golf scores</h2><CalendarDays size={21} /></div>{recentScores.length ? <><div className="score-list">{recentScores.map((score) => <div className="score-row" key={score.id}><span>{formatDate(score.score_date)}</span><strong className="score-value">{score.stableford_score} <small>points</small></strong></div>)}</div><Link className="text-action" to="/scores">Add score <ArrowRight size={15} /></Link></> : <EmptyState title="No golf scores yet." message="Add your first score to keep your golf activity up to date." />}</article>
      <article className="member-card activity-card"><div className="card-heading"><h2>Draws & prizes</h2><Trophy size={21} /></div>{currentDraw && <div className="detail-line"><span>Current draw</span><strong>{currentDraw.draw_name || formatDate(currentDraw.draw_month)}</strong></div>}{latestWinner && <div className="detail-line"><span>Latest prize</span><strong>{statusLabel(latestWinner.payout_status || latestWinner.verification_status)}</strong></div>}{!currentDraw && !latestWinner && <p>When a draw is published or you win a prize, it will appear here.</p>}<div className="member-actions" style={{ marginTop: 16 }}><Link className="text-action" to="/draws">View draws <ArrowRight size={15} /></Link><Link className="text-action" to="/winners">View prizes <ArrowRight size={15} /></Link></div></article>
    </div></section>;
}
