import { useEffect, useState } from "react";
import { CalendarDays, CircleDollarSign, Heart, HeartHandshake, Plus, ReceiptText } from "lucide-react";
import { Link } from "react-router-dom";
import { EmptyState, ErrorState, InlineLoading } from "../components/UiStates";
import { getCharities } from "../services/charityService";
import { createDonation, getDonations } from "../services/donationService";
import { getSubscriptions } from "../services/subscriptionService";
import { apiMessage, currencyValue, formatDate, statusLabel } from "./memberUtils";
import "./MemberPages.css";

const freshForm = { charity_id: "", amount: "" };

export default function Donations() {
  const [donations, setDonations] = useState([]), [subscriptions, setSubscriptions] = useState([]), [charities, setCharities] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [subscriptionError, setSubscriptionError] = useState("");
  const [form, setForm] = useState(freshForm), [formError, setFormError] = useState(""), [success, setSuccess] = useState(""), [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(""); setSubscriptionError(""); const [donationResult, subscriptionResult, charityResult] = await Promise.allSettled([getDonations(), getSubscriptions(), getCharities({ active: true })]); if (donationResult.status === "fulfilled") setDonations(donationResult.value.data.donations || []); else setError(apiMessage(donationResult.reason, "We couldn’t load your donation history.")); if (subscriptionResult.status === "fulfilled") setSubscriptions(subscriptionResult.value.data.subscriptions || []); else setSubscriptionError("Your membership contribution details are temporarily unavailable."); if (charityResult.status === "fulfilled") setCharities(charityResult.value.data.charities || []); else setError((current) => current || "We couldn’t load charities for a new donation."); setLoading(false); };
  useEffect(() => { load(); }, []);
  const submit = async (event) => { event.preventDefault(); setFormError(""); setSuccess(""); const amount = Number(form.amount); if (!form.charity_id) return setFormError("Please select a charity."); if (!Number.isFinite(amount) || amount <= 0) return setFormError("Donation amount must be greater than 0."); setSaving(true); try { const { data } = await createDonation({ charity_id: form.charity_id, amount }); setSuccess(data.message || "Donation created successfully."); setForm(freshForm); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t record this donation.")); } finally { setSaving(false); } };
  const activeSubscription = subscriptions.find((subscription) => subscription.status === "active"); const subscriptionDonation = activeSubscription ? donations.find((donation) => donation.donation_type === "subscription" && donation.subscription_id === activeSubscription.id) : null;
  if (loading) return <section className="member-page"><div className="member-card"><InlineLoading label="Loading your contributions…" /></div></section>;
  return <section className="member-page"><header className="member-header"><div><p className="page-eyebrow">Your giving</p><h1>Donations that matter.</h1><p>Keep a clear record of the charities you support through Digital Heroes.</p></div></header>{error ? <div className="member-card"><ErrorState message={error} onRetry={load} /></div> : <>{subscriptionError && <div className="notice">{subscriptionError}</div>}{formError && <div className="form-error">{formError}</div>}{success && <div className="form-success">{success}</div>}
    {activeSubscription && <article className="member-card current-contribution-card"><div className="card-heading"><h2>Current charity contribution</h2><HeartHandshake size={21} /></div>{activeSubscription.charities ? <div className="current-contribution-content"><div className="charity-preview">{activeSubscription.charities.image_url && <img src={activeSubscription.charities.image_url} alt="" />}<div><strong>{activeSubscription.charities.name}</strong>{activeSubscription.charity_percentage !== undefined && <span>{activeSubscription.charity_percentage}% of your active subscription is recorded as a charity contribution.</span>}</div></div><div className="contribution-facts">{subscriptionDonation?.amount !== undefined && <div><CircleDollarSign size={17} /><span>Recorded contribution</span><strong>{currencyValue(subscriptionDonation.amount, subscriptionDonation.currency)}</strong></div>}{activeSubscription.renewal_date && <div><CalendarDays size={17} /><span>Renewal date</span><strong>{formatDate(activeSubscription.renewal_date)}</strong></div>}</div><Link className="text-action" to={`/charities/${activeSubscription.charities.id}`}>View charity details</Link></div> : <EmptyState title="Charity details are unavailable." message="Your active subscription does not include a linked charity record." />}</article>}
    <div className="donations-layout"><article className="member-card donation-form-card"><div className="card-heading"><h2>Make an independent donation</h2><Heart size={21} /></div><p className="notice">Your donation will be added to your giving history.</p><form onSubmit={submit}><div className="field-grid donation-field-grid"><label className="form-field">Supporting charity<select required value={form.charity_id} onChange={(event) => setForm({ ...form, charity_id: event.target.value })}><option value="">Select a charity</option>{charities.map((charity) => <option key={charity.id} value={charity.id}>{charity.name}</option>)}</select></label><label className="form-field">Donation amount<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} /><span className="field-help">Enter the amount to record.</span></label></div><div className="form-actions"><button className="action-button" disabled={saving}>{saving ? <InlineLoading label="Recording…" /> : <><Plus size={17} /> Record donation</>}</button></div></form></article>
      <article className="member-card donation-history-card"><div className="card-heading"><h2>Donation history</h2><ReceiptText size={21} /></div>{donations.length ? <div className="donation-history-list">{donations.map((donation) => <article className="donation-row" key={donation.id}><div className="donation-row-main"><div className="donation-icon"><HeartHandshake size={18} /></div><div><strong>{donation.charities?.name || "Charity unavailable"}</strong><span>{formatDate(donation.created_at) || "Date unavailable"}</span></div></div><div className="donation-row-meta">{donation.donation_type && <span className="donation-type">{statusLabel(donation.donation_type)}</span>}{donation.status && <span className={`status-badge ${donation.status}`}>{statusLabel(donation.status)}</span>}{donation.amount !== undefined && <strong>{currencyValue(donation.amount, donation.currency)}</strong>}</div></article>)}</div> : <EmptyState title="No donations recorded yet." message="When you make a contribution, its charity and amount will appear here." />}</article></div>
  </>}</section>;
}
