import { useEffect, useState } from "react";
import { ArrowLeft, CalendarDays, CircleDollarSign, Gift, Hash, TicketCheck, Trophy } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { EmptyState, ErrorState, InlineLoading } from "../components/UiStates";
import NumberSet from "../components/NumberSet";
import { createDrawEntry, deleteDrawEntry, getDraw, getMyDrawEntry } from "../services/drawService";
import { apiMessage, currencyValue, formatDate, formatDrawMonth, statusLabel } from "./memberUtils";
import "./MemberPages.css";
import "./DrawPages.css";


export default function DrawDetails() {
  const { id } = useParams(); const [draw, setDraw] = useState(null), [entry, setEntry] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [selectedNumbers, setSelectedNumbers] = useState([]), [entryError, setEntryError] = useState(""), [success, setSuccess] = useState(""), [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); setError(""); setEntryError(""); try { const { data } = await getDraw(id); setDraw(data.draw); try { const entryResponse = await getMyDrawEntry(id); setEntry(entryResponse.data.entry || null); } catch (entryRequestError) { if (entryRequestError.response?.status === 404) setEntry(null); else setEntryError(apiMessage(entryRequestError, "We couldn’t load your participation status.")); } } catch (requestError) { setError(apiMessage(requestError, "We couldn’t load this draw.")); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [id]);
  const toggleNumber = (number) => { setEntryError(""); setSelectedNumbers((current) => current.includes(number) ? current.filter((value) => value !== number) : current.length < 5 ? [...current, number].sort((a, b) => a - b) : current); };
  const saveEntry = async () => { if (selectedNumbers.length !== 5) return setEntryError("Choose exactly 5 unique numbers."); setSaving(true); setEntryError(""); setSuccess(""); try { const { data } = await createDrawEntry(id, { numbers: selectedNumbers }); setEntry(data.entry); setSuccess(data.message || "Draw entry created successfully."); } catch (requestError) { setEntryError(apiMessage(requestError, "We couldn’t create your draw entry.")); } finally { setSaving(false); } };
  const removeEntry = async () => { setSaving(true); setEntryError(""); setSuccess(""); try { const { data } = await deleteDrawEntry(id); setEntry(null); setSelectedNumbers([]); setSuccess(data.message || "Draw entry deleted successfully."); } catch (requestError) { setEntryError(apiMessage(requestError, "We couldn’t delete your draw entry.")); } finally { setSaving(false); } };
  if (loading) return <section className="member-page"><div className="member-card"><InlineLoading label="Loading draw details…" /></div></section>;
  if (error || !draw) return <section className="member-page"><Link className="text-action back-link" to="/draws"><ArrowLeft size={16} /> All draws</Link><div className="member-card"><ErrorState message={error || "Draw not found."} onRetry={load} /></div></section>;
  const prizeTiers = [[draw.status === "published" ? "Five matches" : null, draw.status === "published" ? draw.jackpot_amount : null], ["Four matches", draw.four_match_pool], ["Three matches", draw.three_match_pool], [draw.status === "completed" && draw.jackpot_rollover ? "Next jackpot" : null, draw.status === "completed" && draw.jackpot_rollover ? draw.jackpot_amount : null]].filter(([label, amount]) => label && amount !== null && amount !== undefined);
  return <section className="member-page"><Link className="text-action back-link" to="/draws"><ArrowLeft size={16} /> All draws</Link><header className="member-header draw-detail-header"><div><p className="page-eyebrow">Monthly draw</p><h1>{draw.draw_name || "Monthly draw"}</h1><p>{draw.draw_month && <><CalendarDays size={16} /> {formatDrawMonth(draw.draw_month)}</>}</p></div><span className={`status-badge ${draw.status}`}>{statusLabel(draw.status)}</span></header>{entryError && <div className="form-error">{entryError}</div>}{success && <div className="form-success">{success}</div>}
    <div className="draw-detail-layout"><article className="member-card draw-overview-card"><div className="card-heading"><h2>Draw overview</h2><Gift size={21} /></div><div className="detail-list">{draw.draw_type && <div className="detail-line"><span>Draw type</span><strong>{statusLabel(draw.draw_type)}</strong></div>}{draw.published_at && <div className="detail-line"><span>Published</span><strong>{formatDate(draw.published_at)}</strong></div>}{draw.total_prize_pool !== null && draw.total_prize_pool !== undefined && <div className="detail-line"><span>Total prize pool</span><strong>{currencyValue(draw.total_prize_pool, draw.currency)}</strong></div>}{draw.jackpot_rollover !== null && draw.jackpot_rollover !== undefined && <div className="detail-line"><span>Jackpot rollover</span><strong>{draw.jackpot_rollover ? "Yes" : "No"}</strong></div>}</div></article>
      <article className="member-card winning-card"><div className="card-heading"><h2>Winning numbers</h2><Trophy size={21} /></div>{Array.isArray(draw.winning_numbers) && draw.winning_numbers.length ? <NumberSet numbers={draw.winning_numbers} /> : <EmptyState title="Winning numbers are not available." message="They will appear here when they are recorded for this draw." />}</article></div>
    {prizeTiers.length > 0 && <article className="member-card prize-card"><div className="card-heading"><h2>Recorded prize tiers</h2><CircleDollarSign size={21} /></div><div className="prize-tier-grid">{prizeTiers.map(([label, amount]) => <div key={label}><span>{label}</span><strong>{currencyValue(amount, draw.currency)}</strong></div>)}</div></article>}
    <article className="member-card participation-card"><div className="card-heading"><h2>Your participation</h2><TicketCheck size={21} /></div>{entry ? <div className="entry-content"><p>Your numbers are recorded for this draw.</p><NumberSet numbers={entry.numbers} className="winning-numbers entry-numbers" label="Your numbers" /><div className="entry-match-status">{entry.matched_five ? "Five matching numbers recorded" : entry.matched_four ? "Four matching numbers recorded" : entry.matched_three ? "Three matching numbers recorded" : null}</div><button className="quiet-button danger-action" onClick={removeEntry} disabled={saving}>{saving ? <InlineLoading label="Removing…" /> : "Remove entry"}</button></div> : draw.status === "published" ? <div className="entry-content"><p>Choose five unique numbers from 1 to 45 to create your entry. You’ll need an active subscription to enter.</p><div className="number-picker" role="group" aria-label="Choose five draw numbers">{Array.from({ length: 45 }, (_, index) => index + 1).map((number) => <button type="button" className={selectedNumbers.includes(number) ? "selected" : ""} onClick={() => toggleNumber(number)} aria-pressed={selectedNumbers.includes(number)} key={number}>{number}</button>)}</div><p className="selection-count">{selectedNumbers.length} of 5 numbers selected</p><button className="action-button" onClick={saveEntry} disabled={saving || selectedNumbers.length !== 5}>{saving ? <InlineLoading label="Saving…" /> : "Create entry"}</button></div> : <EmptyState title="Entry is not available for this draw." message="Entries open when a draw is published." />}</article>
  </section>;
}
