import { useEffect, useState } from "react";
import { CalendarClock, HeartHandshake, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { ConfirmationDialog, EmptyState, ErrorState, InlineLoading } from "../components/UiStates";
import { getCharities } from "../services/charityService";
import { cancelSubscription, createSubscription, getSubscriptions } from "../services/subscriptionService";
import { apiMessage, currencyValue, formatDate, statusLabel } from "./memberUtils";
import "./MemberPages.css";

const freshForm = { plan_type: "monthly", amount: "", charity_id: "", charity_percentage: "10", renewal_date: "" };
export default function Subscription() {
  const [subscriptions, setSubscriptions] = useState([]), [charities, setCharities] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [form, setForm] = useState(freshForm), [formError, setFormError] = useState(""), [success, setSuccess] = useState(""), [saving, setSaving] = useState(false), [cancelTarget, setCancelTarget] = useState(null), [cancelling, setCancelling] = useState(false);
  const load = async () => { setLoading(true); setError(""); const [subscriptionResult, charityResult] = await Promise.allSettled([getSubscriptions(), getCharities({ active: true })]); if (subscriptionResult.status === "fulfilled") setSubscriptions(subscriptionResult.value.data.subscriptions || []); else setError(apiMessage(subscriptionResult.reason, "We couldn’t load your subscriptions.")); if (charityResult.status === "fulfilled") setCharities(charityResult.value.data.charities || []); else setError((current) => current || "We couldn’t load charities for a new subscription."); setLoading(false); };
  useEffect(() => { load(); }, []);
  const active = subscriptions.find((subscription) => subscription.status === "active"); const display = active || subscriptions[0];
  const submit = async (event) => { event.preventDefault(); setFormError(""); setSuccess(""); const amount = Number(form.amount), percentage = Number(form.charity_percentage); if (!form.charity_id) return setFormError("Please select a charity."); if (!Number.isFinite(amount) || amount <= 0) return setFormError("The subscription amount must be greater than 0."); if (!Number.isFinite(percentage) || percentage < 10 || percentage > 100) return setFormError("Charity contribution must be between 10% and 100%."); setSaving(true); try { const payload = { plan_type: form.plan_type, amount, charity_id: form.charity_id, charity_percentage: percentage, ...(form.renewal_date ? { renewal_date: form.renewal_date } : {}) }; const { data } = await createSubscription(payload); setSuccess(data.message || "Subscription created."); setForm(freshForm); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t create this subscription.")); } finally { setSaving(false); } };
  const confirmCancel = async () => { if (!cancelTarget) return; setCancelling(true); setFormError(""); try { const { data } = await cancelSubscription(cancelTarget.id); setSuccess(data.message || "Subscription cancelled."); setCancelTarget(null); await load(); } catch (requestError) { setFormError(apiMessage(requestError, "We couldn’t cancel this subscription.")); setCancelTarget(null); } finally { setCancelling(false); } };
  if (loading) return <section className="member-page"><div className="member-card"><InlineLoading label="Loading your membership…" /></div></section>;
  return <section className="member-page"><header className="member-header"><div><p className="page-eyebrow">Subscription</p><h1>Your subscription.</h1><p>See your subscription status and the charity you support.</p></div></header>{error && <div className="page-error"><ErrorState message={error} onRetry={load} /></div>}{formError && <div className="form-error">{formError}</div>}{success && <div className="form-success">{success}</div>}
    {display ? <div className="subscription-layout"><article className="member-card subscription-summary"><div className="card-heading"><h2>Subscription details</h2><ShieldCheck size={21} /></div><div className="subscription-status"><span className={`status-badge ${display.status}`}>{statusLabel(display.status)}</span></div><h3 className="plan-title">{display.plan_type || "Subscription"}</h3><div className="detail-list">{display.amount !== undefined && <div className="detail-line"><span>Amount</span><strong>{currencyValue(display.amount, display.currency)}</strong></div>}{(display.start_date || display.created_at) && <div className="detail-line"><span>Started</span><strong>{formatDate(display.start_date || display.created_at)}</strong></div>}{display.renewal_date && <div className="detail-line"><span>Renewal date</span><strong>{formatDate(display.renewal_date)}</strong></div>}{display.cancelled_at && <div className="detail-line"><span>Cancelled</span><strong>{formatDate(display.cancelled_at)}</strong></div>}</div>{display.status !== "cancelled" && <button className="text-action danger-action" onClick={() => setCancelTarget(display)}>Cancel subscription</button>}</article>
      <article className="member-card"><div className="card-heading"><h2>Your charity</h2><HeartHandshake size={21} /></div>{display.charities ? <><div className="charity-preview">{display.charities.image_url && <img src={display.charities.image_url} alt="" />}<div><strong>{display.charities.name}</strong>{display.charity_percentage !== undefined && <span>{display.charity_percentage}% contribution</span>}</div></div><Link className="text-action" to={`/charities/${display.charities.id}`}>View charity</Link></> : <EmptyState title="No charity linked yet." message="This subscription isn’t linked to a charity yet." />}</article></div> : !error && <div className="member-card"><EmptyState title="No subscription yet." message="Choose a plan and charity below to subscribe." /></div>}
    {!active && <article className="member-card form-card"><div className="card-heading"><h2>Subscribe</h2><CalendarClock size={21} /></div><p className="notice">Choose a plan and charity to begin your Digital Heroes journey. Your subscription will appear here once it is created.</p><p className="small-print">Enter the amount that applies to your plan. Plan prices are confirmed separately by Digital Heroes.</p><form onSubmit={submit}><div className="field-grid"><label className="form-field">Plan type<select value={form.plan_type} onChange={(e) => setForm({ ...form, plan_type: e.target.value })}><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label className="form-field">Amount<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /><span className="field-help">Enter the amount for this subscription.</span></label><label className="form-field">Supporting charity<select required value={form.charity_id} onChange={(e) => setForm({ ...form, charity_id: e.target.value })}><option value="">Select a charity</option>{charities.map((charity) => <option key={charity.id} value={charity.id}>{charity.name}</option>)}</select></label><label className="form-field">Charity contribution (%)<input required type="number" min="10" max="100" step="1" value={form.charity_percentage} onChange={(e) => setForm({ ...form, charity_percentage: e.target.value })} /><span className="field-help">Between 10% and 100%.</span></label><label className="form-field">Renewal date (optional)<input type="date" value={form.renewal_date} onChange={(e) => setForm({ ...form, renewal_date: e.target.value })} /></label></div><div className="form-actions"><button className="action-button" disabled={saving}>{saving ? <InlineLoading label="Saving…" /> : "Subscribe"}</button></div></form></article>}
    <ConfirmationDialog open={Boolean(cancelTarget)} title="Cancel this subscription?" message="Your subscription will be cancelled. You can subscribe again later." confirmLabel={cancelling ? "Cancelling…" : "Cancel subscription"} onConfirm={confirmCancel} onCancel={() => !cancelling && setCancelTarget(null)} />
  </section>;
}
